### ISSUE TITLE
Missing terraform lint recursive flag

### ISSUE THREAD

**Issue by samuelarogbonlo** [ChainSafe/forest-iac#123]
**Issue summary**
During the last refactor of the forest node terraform directory we may have missed the `--recursive` flag for the terraform lint

**Task summary**

- [x] Enable the terraform lint `--recursive` flag
- [x] Fix all linting errors 

**Acceptance Criteria**

- [x] Terraform code should pass the linting checks 

**Other information and links**
