### ISSUE TITLE
Benchmark service improvements

### ISSUE THREAD

**Issue by sudo-shashank** [ChainSafe/forest-iac#234]
**Issue summary**

This issue is created from discussion over [PR](https://github.com/ChainSafe/forest-iac/pull/122)
**Task summary**

- [ ] Add unit tests 
- [ ] Use docker images for forest and lotus to simplify dependencies 
- [ ] Investigate on a CSV migration plan, how to view results and compare easily
- [ ] Add peek RSS and VSZ metric to benchmark output
- [ ] Use template env instead of echoing evn vars

**Acceptance Criteria**
 

**Other information and links**

**Comment by lemmih** [comment]
Do not track VSZ unless you can convince me it isn't useless.
